const WEATHER_TYPES = {


    GET_CURRENT_WEATHER_BEGIN:'GET_CURRENT_WEATHER_BEGIN',
    GET_CURRENT_WEATHER_SUCCESS:'GET_CURRENT_WEATHER_SUCCESS',
    GET_CURRENT_WEATHER_FAILURE:'GET_CURRENT_WEATHER_FAILURE',

    GET_WEATHER_FORECAST_BEGIN:'GET_WEATHER_FORECAST_BEGIN',
    GET_WEATHER_FORECAST_SUCCESS:'GET_WEATHER_FORECAST_SUCCESS',
    GET_WEATHER_FORECAST_FAILURE:'GET_WEATHER_FORECAST_FAILURE'

  };
  
  export default WEATHER_TYPES;
  